[package]
name = "alfred-pinboard-rs"
version = "0.14.5"
authors = ["Hamid Ghadyani <hamid@hamid.cc>"]

[dependencies]
# We'll use git until rusty-pin is published as a crate (if ever?!)
# rusty-pin = { path = "../rusty-pin" }
rusty-pin = { git = "https://github.com/spamwax/rusty-pin", branch = "master" }
# alfred = { path = "../alfred-rs" , features = ["updater"]}
alfred = "4.0.1"
# alfred-rs = { path = "../alfred-workflow" }
alfred-rs = "0.4"
chrono = { version = "0.4", features = ["serde"] }

serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"

structopt = "0.2"

semver = "0.9"

failure = "0.1.2"
dirs = "1.0"

if_chain = "0.1.3"

log = "0.4"
env_logger = "0.5.13"

# clippy = { version = "*", optional = true }

[features]
# dev = ["clippy"]

